#!/bin/sh

# popolate /web if empty

if [ ! -d /web/html ]; then
  mkdir /web/html
  echo "<html>
  <body>
    <h1>It Works!</h1>
    Nginx on Alpine with Docker container <a href=https://hub.docker.com/r/nimmis/alpine-nginx/>nimmis/alpine-nginx</a>
  </body>
</html>" > /web/html/index.html
  chown -R nginx.nginx /web/html
fi

if [ ! -d /web/config ]; then
  mkdir /web/config
  chown -R nginx.nginx /web/config
fi

if [ ! -d /web/logs ]; then
  mkdir /web/logs
  chown -R nginx.nginx /web/logs
fi

if [ ! -f /web/config/httpd.conf ]; then
  cp -R /etc/nginx/* /web/config/
  chown -R nginx.nginx /web/config
fi

if [ ! -d /web/run ]; then
  mkdir /web/run
fi

if [ ! -d /web/cgi-bin ]; then
  mkdir /web/cgi-bin
  chown -R nginx.nginx /web/cgi-bin
fi

